/**
 * This file was generated by Anything. You may edit it but doing so may cause
 * issues in your app.
 */
import { getToken } from '@auth/core/jwt';

const AUTH_SECRET = process.env.AUTH_SECRET || '';
const AUTH_URL = process.env.AUTH_URL || '';

export async function GET(request: Request) {
	const [token, jwt] = await Promise.all([
		getToken({
			req: request,
			secret: AUTH_SECRET,
			salt: 'authjs.session-token',
			secureCookie: AUTH_URL.startsWith('https'),
			raw: true,
		}),
		getToken({
			req: request,
			secret: AUTH_SECRET,
			salt: 'authjs.session-token',
			secureCookie: AUTH_URL.startsWith('https'),
		}),
	]);

	if (!jwt) {
		return new Response(JSON.stringify({ error: 'Unauthorized' }), {
			status: 401,
			headers: {
				'Content-Type': 'application/json',
			},
		});
	}

	return new Response(
		JSON.stringify({
			jwt: token,
			user: {
				id: jwt.sub,
				email: jwt.email,
				name: jwt.name,
			},
		}),
		{
			headers: {
				'Content-Type': 'application/json',
			},
		}
	);
}


