/**
 * This file was generated by Anything. You may edit it but doing so may cause
 * issues in your app.
 */
import { useCallback } from 'react';
import { signIn, signOut } from "next-auth/react";

interface SignInOptions {
  callbackUrl?: string;
  [key: string]: unknown;
}

function useAuth() {
  const callbackUrl = typeof window !== 'undefined' 
    ? new URLSearchParams(window.location.search).get('callbackUrl')
    : null;

  const signInWithCredentials = useCallback((options: SignInOptions) => {
    return signIn("credentials-signin", {
      ...options,
      callbackUrl: callbackUrl ?? options.callbackUrl
    });
  }, [callbackUrl])

  const signUpWithCredentials = useCallback((options: SignInOptions) => {
    return signIn("credentials-signup", {
      ...options,
      callbackUrl: callbackUrl ?? options.callbackUrl
    });
  }, [callbackUrl])

  const signInWithGoogle = useCallback((options: SignInOptions) => {
    return signIn("google", {
      ...options,
      callbackUrl: callbackUrl ?? options.callbackUrl
    });
  }, [callbackUrl]);
  const signInWithFacebook = useCallback((options: SignInOptions) => {
    return signIn("facebook", options);
  }, []);
  const signInWithTwitter = useCallback((options: SignInOptions) => {
    return signIn("twitter", options);
  }, []);

  return {
    signInWithCredentials,
    signUpWithCredentials,
    signInWithGoogle,
    signInWithFacebook,
    signInWithTwitter,
    signOut,
  }
}

export default useAuth;


