/**
 * This file was generated by Anything. You may edit it but doing so may cause
 * issues in your app.
 */
import * as React from 'react';
import { useSession } from "next-auth/react";

interface UserSession {
  user?: {
    id?: string;
    email?: string | null;
    name?: string | null;
    image?: string | null;
  } | null;
}

const useUser = () => {
  const { data: session, status } = useSession();
  const id = (session?.user as unknown as UserSession['user'])?.id

  const [user, setUser] = React.useState<UserSession['user'] | null>(session?.user ?? null);

  const fetchUser = React.useCallback(async (session: UserSession) => {
  return session?.user;
}, [])

  const refetchUser = React.useCallback(() => {
    if(process.env.NEXT_PUBLIC_CREATE_ENV === "PRODUCTION") {
      if (id) {
        fetchUser(session as UserSession).then((userData) => {
          setUser(userData ?? null);
        });
      } else {
        setUser(null);
      }
    }
  }, [fetchUser, id, session])

  React.useEffect(refetchUser, [refetchUser]);

  if (process.env.NEXT_PUBLIC_CREATE_ENV !== "PRODUCTION") {
    return { user, data: session?.user || null, loading: status === 'loading', refetch: refetchUser };
  }
  return { user, data: user, loading: status === 'loading' || (status === 'authenticated' && !user), refetch: refetchUser };
};

export { useUser }

export default useUser;


